### PR TITLE
Added footer #9

### PR DESCRIPTION
**Pull request by AnushkaMittal21**
## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.
- [x] I am a participant of Hacktoberfest 2022

### CODE REVIEW

**Comment by KiranAminPanjwani** [comment]
Your work is awesome!✨
Please provide details in your comment. Thank you.😊

**Comment by AnushkaMittal21** [comment]
Thank you!
Which details I have to provide?

**Comment by AnushkaMittal21** [comment]
Hey, Please can you look into the solution of my issue and if its correct please merge it in main.

**Review by KiranAminPanjwani — APPROVED** [review]
Happy Contributing! 😊🎉

**Pull request merged**
