### PR TITLE
adds website deploy hyperlink

### PR DESCRIPTION
**Pull request by Aum3010**
## 🛠️ Fixes Issue: 
Adds hyperlink instead of opening on the same page for deployment

## 👨‍💻 Changes proposed:

Adds a button to the GitHub docs for contributors to access the website in the new window

## ✔️ Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.
- [x] I am a participant of Hacktoberfest 2022

---
## Screenshots 

Screenshot 2022-10-03 at 10 34 26 PM

### CODE REVIEW

**Comment by KiranAminPanjwani** [comment]
No dear, I don't like the icon actually. Instead, we can use WORK FLASH's globe image inside the anchor tag. 😊

**Comment by Aum3010** [comment]
Hello, Thank you for your suggestion  Kindly review this logo

worldwide

**Comment by KiranAminPanjwani** [comment]
> Hello, Thank you for your suggestion Kindly review this logo
> 
> worldwide

This is awesome, but this will not be visible in the dark mode. try a red and light pink.

**Comment by Aum3010** [comment]
icons8-earth-60

This seems better

PS. My bad for not considering both light and dark mode

**Review by KiranAminPanjwani — APPROVED** [review]
Awesome! ✨
Happy Contributing! 😊🎉

**Pull request merged**
